name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  IMAGE: airflow-plugins-dependencies # image name
  GAR_REGION: asia-southeast1rtifact registry zone
  GAR_REPO: airflow-gke # artifact registry repository

jobs:
  deploy-image-to-gar:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v3

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

    - name: install the gcloud cli
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: build and push the docker image
      run: |
        docker build \
          --tag "${{env.GAR_REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.GAR_REPO}}/${{env.IMAGE}}:latest" \
          --tag "${{env.GAR_REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.GAR_REPO}}/${{env.IMAGE}}:${{env.COMMIT_SHORT_SHA}}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
        gcloud auth configure-docker ${{env.GAR_REGION}}-docker.pkg.dev --quiet
        docker push "${{env.GAR_REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.GAR_REPO}}/${{env.IMAGE}}:latest"
        docker push "${{env.GAR_REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.GAR_REPO}}/${{env.IMAGE}}:${{env.COMMIT_SHORT_SHA}}"