name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: data-team-cluster    # cluster name
  GKE_ZONE: asia-southeast1-a   # cluster zone
  IMAGE: airflow-plugins-dependencies # image name
  IMAGE_TAG: 1.0.1 # image tag
  GAR_REGION: asia-southeast1
  GAR_ZONE: asia-southeast1-a # artifact registry zone
  GAR_REPO: airflow-gke # artifact registry repository

jobs:
  deploy-image-to-gar:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/auth@v1
      with:
        # project_id: ${{ env.PROJECT_ID }}
        # service_account_key: ${{ secrets.GKE_SA_KEY }}
        # export_default_credentials: true
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: build and push the docker image\
      run: |
        docker build \
          --tag "${{env.GAR_REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.GAR_REPO}}/${{env.IMAGE}}:${{env.IMAGE_TAG}}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
        gcloud auth configure-docker ${{env.GAR_REGION}}.pkg.dev --quiet
        docker push "${{env.GAR_REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.GAR_REPO}}/${{env.IMAGE}}:${{env.IMAGE_TAG}}"